name: a1
channels:
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - annotated-types=0.6.0
  - anyio=4.10.0
  - aom=3.12.1
  - appdirs=1.4.4
  - arrow-cpp=21.0.0
  - attrs=25.4.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.21.4
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.7
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.0
  - aws-sdk-cpp=1.11.638
  - blas=1.0
  - bottleneck=1.4.2
  - brotlicffi=1.2.0.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - certifi=2026.1.4
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.2.1
  - dataclasses=0.8
  - datasets=4.5.0
  - dav1d=1.2.1
  - dill=0.4.0
  - docker-pycreds=0.4.0
  - eval_type_backport=0.3.1
  - expat=2.7.3
  - filelock=3.20.3
  - fontconfig=2.15.0
  - freetype=2.14.1
  - fribidi=1.0.16
  - fsspec=2026.1.0
  - gettext=0.21.0
  - gflags=2.2.2
  - gitdb=4.0.12
  - gitpython=3.1.46
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.2.2
  - google-cloud-sdk=555.0.0
  - graphite2=1.3.14
  - h11=0.16.0
  - harfbuzz=12.3.0
  - hf-xet=1.1.8
  - httpcore=1.0.9
  - httpx=0.28.1
  - huggingface_hub=0.34.4
  - icu=73.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - intel-openmp=2025.0.0
  - jansson=2.14
  - jinja2=3.1.6
  - jpeg=9f
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20250814.1
  - libavif=1.3.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcurl=8.18.0
  - libdeflate=1.22
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libglib=2.86.3
  - libgomp=15.2.0
  - libgrpc=1.74.1
  - libhwloc=2.12.1
  - libiconv=1.16
  - libidn2=2.3.8
  - libkrb5=1.22.1
  - libmpdec=4.0.0
  - libnghttp2=1.67.1
  - libopenjpeg=2.5.4
  - libpng=1.6.54
  - libprotobuf=6.33.0
  - libre2-11=2025.11.05
  - libsentencepiece=0.2.1
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libtorch=2.8.0
  - libunistring=1.3
  - libuuid=1.41.5
  - libuv=1.48.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mistral-common=1.8.3
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multiprocess=0.70.18
  - ncurses=6.5
  - networkx=3.6.1
  - numexpr=2.14.1
  - numpy=2.4.1
  - numpy-base=2.4.1
  - openssl=3.6.1
  - opentelemetry-api=1.38.0
  - orc=2.2.0
  - packaging=25.0
  - pandas=2.3.3
  - pcre2=10.46
  - pillow=12.1.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.0
  - protobuf=6.33.0
  - psutil=7.0.0
  - pthread-stubs=0.3
  - pyarrow=21.0.0
  - pycountry=24.6.1
  - pycparser=2.23
  - pydantic=2.12.4
  - pydantic-core=2.41.5
  - pydantic-extra-types=2.11.0
  - pysocks=1.7.1
  - python=3.13.11
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.3
  - python-xxhash=3.5.0
  - python_abi=3.13
  - pytorch=2.8.0
  - pytz=2025.2
  - pyyaml=6.0.3
  - re2=2025.11.05
  - readline=8.3
  - referencing=0.37.0
  - regex=2025.11.3
  - requests=2.32.5
  - rpds-py=0.28.0
  - s2n=1.5.14
  - safetensors=0.7.0
  - sentencepiece=0.2.1
  - sentencepiece-python=0.2.1
  - sentencepiece-spm=0.2.1
  - sentry-sdk=2.45.0
  - setproctitle=1.3.7
  - setuptools=80.10.1
  - six=1.17.0
  - sleef=3.5.1
  - smmap=4.0.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - sqlite=3.51.1
  - sympy=1.14.0
  - tbb=2022.3.0
  - tbb-devel=2022.3.0
  - tiktoken=0.12.0
  - tk=8.6.15
  - tokenizers=0.22.2
  - tqdm=4.67.1
  - transformers=4.57.1
  - typing=3.10.0.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025c
  - urllib3=2.6.3
  - utf8proc=2.6.1
  - wandb=0.24.1
  - wheel=0.46.3
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xxhash=0.8.0
  - xz=5.6.4
  - yaml=0.2.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
